### ISSUE TITLE
Easy way to remove CodeQ.Site from whole package?

### ISSUE THREAD

**Issue by timvonwerne** [rolandschuetz/Neos-Skeleton#10]
Hey there,
I installed the site just like it is described in the "Getting started" guide.

The folders name now is Vendor.Site but obviously in the source code, everything is still rendered as CodeQ.Site:...

Is there any easy way to get rid of this and use Vendor.Site there without having to change it in every single file?

Cheers
Tim

---

- Neos Version: latest
- Skeleton Version: latest
- Environment: Ubuntu server with PHP 7.3

**Comment by rolandschuetz** [comment]
Hello Tim,

the 2. step here should take care of this: https://github.com/code-q-web-factory/Neos-Skeletonblob/master/docs/GETTING_STARTED.md#start-a-new-git-project

Did you execute the Linux find operation on your system?

**Comment by timvonwerne** [comment]
Hey Roland,
thanks for the hint, totally ignored this after reading "OSX" 🤦

Works perfectly now
