### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by ghost** [rolandschuetz/Neos-Skeleton#14]
What do you think about the open source package by [KaufmannDigital](https://github.com/KaufmannDigital/KaufmannDigital.GDPR.CookieConsent)?

I think this could be a neat addition since ~~winter~~ GDPR is ~~coming~~ here.

Yeah, there are many free and paid providers. But a solution just for Neos is so much cooler.

Mittwald, for example, uses and sponsors this (example on their homepage).

**Comment by rolandschuetz** [comment]
Yeah, heard good things about your cookie banner. Could you make a pull request with preconfigured Google Analytics stuff from the analytics package and some basic explanations in the settings yaml.

**Comment by rolandschuetz** [comment]
Is this still in process?

**Comment by rolandschuetz** [comment]
Seems like you're not working on this anymore, so going to close this.

This feature doesn't really require Neos, could be also implemented e.g. just by using CookieBot.
