### ISSUE TITLE
[SUGGEST] CSS-only Responsive Multi-level Navigation Menu

### ISSUE THREAD

**Issue by ghost** [rolandschuetz/Neos-Skeleton#18]
Hi Roland,
your skeleton is a realy nice way to start new NeosCMS Projects, thanks!

I'm completely new to the Neos and Fusion world, so it took me over a week of work to implement this very simple "CSS-only Responsive Multi-level Navigation Menu":
- https://w3bits.com/css-responsive-nav-menu/ (article)
- https://w3bits.com/labs/css-responsive-nav/ (demo)

I was wondering how much more knowledge I needed to render the Link in two different ways (no submenu, has submenu),
because I had to learn the "conditional" systaxes for Fusion.

**So, I think an implementation of this navigation in your skeleton would be another additional value for starters and beginners, what do you think?**

_(My working solution ended up with a "Vendor.Name:Component.Header.MenuItemsRenderer" and a "Vendor.Name:Component.Header.SubMenuItemsRenderer", but I think it can be done easier.)_

Have a nice coffee
Salvatore

**Comment by rolandschuetz** [comment]
Hello Salvatore,

on purpose, we wanted to keep the CSS minimal. The skeleton wants to be frontend-agnostic, so you should bring your own styles.

So how did your "Vendor.Name:Component.Header.MenuItemsRenderer" and "Vendor.Name:Component.Header.SubMenuItemsRenderer" end up?

**Comment by ghost** [comment]
Hi Roland,
yes I am with you with the "minimal CSS purpose". For me, it was just hard to first learn more about "fusion" to be able to implement my custom CSS/HTML ;)

I made some screenshots for you.

Header.fusion: https://ibb.co/7SxJd34
Header.MenuItemsRenderer.fusion: https://ibb.co/1ZgsPNh
Header.SubMenuItemsRenderer.fusion: https://ibb.co/nn2WVpp

**Frontend Result**: https://ibb.co/k3cmRzq

So, the "SubMenuItemsRenderer" is calling himself and I build the correct "substrings" with substring + iteration.index ...

_(Optimized for the navigation mentioned in the opening post)_

**Comment by rolandschuetz** [comment]
Yeah, learning Fusion takes a bit of time.

If you move your html `<nav> <div class="container"> ...` until the `<ul>` from `Header.MenuItemsRenderer.fusion` into `Header.fusion`, then you can combine `Header.MenuItemsRenderer.fusion` and `Header.SubMenuItemsRenderer.fusion`.

Cheers,
Roland
