### ISSUE TITLE
Header with own Logo and Theming

### ISSUE THREAD

**Issue by sm2x** [rolandschuetz/Neos-Skeleton#20]
Completely beginner here, how do you customize the Header part (where logo and menus are) on a Multidomain setup?

**Comment by rolandschuetz** [comment]
So if you have a multidomain setup you probably want to make the logo configurable. For that you need to add a property "logo" to the Homepage Document node type, then you can get it with {q(site).property('logo')}. Take a look at how the footer is implemented, it's the same idea.

The menues are build for each domain separate, so you just need to create pages....

Take a look at our beginner course: https://docs.neos.io/cms/building-your-first-website/understanding-rendering

**Comment by sm2x** [comment]
thank you for the tip Roland, so I can also adapt the same procedure for the  background color or image of the heading as well as on format of the Menus?

**Comment by rolandschuetz** [comment]
Yes.

**Comment by rolandschuetz** [comment]
For general questions about Neos please use our https://discuss.neos.io/ forum or the slack channel. Thanks!
