### ISSUE TITLE
Problems with Document Tree

### ISSUE THREAD

**Issue by maxodoble** [rolandschuetz/Neos-Skeleton#27]
Hi,

was trying out neos cms and followed the tutorial in the neos docs, using your neos skeleton.
i am getting weird problems with the document tree:

- pages disapper in the tree browser (after just being created), have to constantly click reload to show them up again
- flushing the cache solves this problem temporarily, until another page gets added, then the new page disappears.

i have posted a question regarding this problem in the neos discuss forum: [neos discuss](https://discuss.neos.io/t/beginner-question-content-tree-problems-in-ui/5843). There you can find a problem description, and a short screencast.

Upon feedback in the forum, i setup a new neos project without your neos skeleton, and imported the Neos.Demo Site. And with this setup, i am not getting the weird doctree problems.

As these are my first tests with Neos, i can't really tell, if the problems i stumbled upon are a bug in the neos skeleton, or a problem with a configuration setting on my side, so i opened this issue here, to let you know.

Any idea?

Thanks,
Max

**Comment by olimination** [comment]
@maxodoble see my update here: https://discuss.neos.io/t/beginner-question-content-tree-problems-in-ui/5843/11

My assumption is that there is an issue with the Footer Cache config which was not yet here in the past.

**Comment by olimination** [comment]
Created a bug report in the Neos UI repo: https://github.com/neos/neos-ui/issues/3248

**Comment by alexander-nitsche** [comment]
I can confirm that this commit fixes the problem in Neos 7 LTS.

P.S.: It would be interesting to get some background information on this problem, which could be interesting for any Neos developer, but especially for beginners.

**Comment by alexander-nitsche** [comment]
As i am anaylzing the Neos / Flow cache currently, i became aware that with the PR #30 the footer gets cached twice: (1) The footer of the homepage (which is editable) and (2) the footer of any other page (which is not editable).

**Comment by rolandschuetz** [comment]
Sounds good time me. Do you see a problem in this?
