### ISSUE TITLE
Could not install new Site

### ISSUE THREAD

**Issue by markusguenther** [rolandschuetz/Neos-Skeleton#7]
It seems that the neos/googleanalytics makes problems with the new Neos version.
I get charset errors even if the rest (without neos/googleanalytics) is working.

Is this just a problem on my Mac or can someone confirm this. The Repository of neos/googleanalytics changed something 8 month ago so normally it should work.

Maybe @rolandschuetz has an idea. If you don't have that. We can just close this issue.

I use latest macOS with latest PHP and MYSQL.

![bildschirmfoto 2019-01-11 um 14 07 49](https://user-images.githubusercontent.com/1014126/51037159-bfa17380-15af-11e9-81e3-32780cc9b45c.png)

**Comment by M-Krieger** [comment]
I had some similar issues and couldn't sort it out. This was the error:
```
An exception occurred while executing 'ALTER TABLE typo3_neos_googleanalytics_domain_model_siteconfiguration ADD CONSTRAINT FK_D675F674694309E4 FOREIGN KEY (site) REFERENCES typo3_neos_domain_model_site (persistence_object_identifier) ON DELETE CASCADE':
```

I had a chat with Roland but we couldn't figure out what's going on and I accepted it as a strange environment issue. I'm also running an up-to-date Mac with php 7.2 and mysql. 5.6.x running many different working neos setups. I accepted it as a strange environment issue and dropped neos/googleanalytics as I didn't need it anyway.

**Comment by markusguenther** [comment]
Yeah I also removed it now, but have on my list to test a plain neos with the package. Because maybe it is an issue in the google analytics package. But they adjusted something in the migration 8 month ago...

But the guy who did this was a linux guy ;)

**Comment by M-Krieger** [comment]
Yeah we also thought about the utf8 migrations but I didn't investigated furthermore.

**Comment by markusguenther** [comment]
Have this on my list ... so when I close this issue you will see that it is a different issue ;)

**Comment by rolandschuetz** [comment]
Hello @markusguenther 

sorry for the late response. The neos/googleanalytics migrations are a bit tricky, we fixed projects some time ago. 

Please add the issue to our [Neos issue tracker](https://github.com/neos/neos-development-collection/issues), it's not an issue of the Neos-Skeleton and can't be fixed inside it.
